[package]
name = "clip_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.14.0"
openh264 = "0.4.4"
serde = "1.0.195"
toml = "0.8.8"
